# make file for 03 chapter

dataTypes: dataTypes.c
	gcc -o dataTypes.exe dataTypes.c

implicitConversion: implicitConversion.c
	gcc -o implicitConversion.exe implicitConversion.c

explicitCast: explicitCast.c
	gcc -o explicitCast.exe explicitCast.c

exercises: exercises.c
	gcc -o exercises.exe exercises.c